name: "leviatrace"

networks:
  levianetwork:
    driver: bridge

services:

  leviathan.api:
    container_name: leviathan.api
    build:
      context: .
      dockerfile: Leviathan.Api/Dockerfile
    environment:
      OTEL_DOTNET_AUTO_HOME: /otel-dotnet-auto
      OTEL_SERVICE_NAME: "Leviathan.Api"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
    ports:
      - "7000:8080"
    networks:
      - levianetwork
      -
  nautilus.app:
    image: nautilus.app
    build:
      context: .
      dockerfile: Nautilus.App/Dockerfile
    networks:
      - levianetwork

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    networks:
      - levianetwork
